### ISSUE TITLE
Question about labeling on eval.py

### ISSUE THREAD

**Issue by kim0207** [dbolya/yolact#100]
First of all, Thank you for your wonderful work.

I want to visualize my predictions with label with each objects id.
For example person1, person2, car1, car2.
Can you tell me how I can show it like that?

**Comment by dbolya** [comment]
I've kinda answered this before but it turns out that person was talking about something else, so I'll paste that answer here:

You'll have to add that yourself, but I can get you started. You want to modify this line to include the index of the person:

https://github.com/dbolya/yolact/blob/f46dc4385a41ed1f2df6716ecf6084081afcbec6/eval.py#L219

Use some data structure to keep track of how many of each class have been detected beforehand and just put that number in the string next to the class. If you want to do a quick and dirty solution you can just replace that with text_str = '%s %d' % (_class, j) but that's not exactly what you want.

**Comment by kim0207** [comment]
I followed what you have wrote but it appears  count the whole number of objects.

Based on your reply, it gives me as:
car1, car2, person3, person4, person5

But I want to count and give ids for each same number of class. For example If I had two cars and three person,
I want car1, car2, person1, person2, person3.

**Comment by dbolya** [comment]
Yeah that's why I said it's not exactly what you want. You'll need to count the number of instances of the class yourself with a dictionary. Something like this will do:
```python
# Put this outside of the loop, e.g., line 207:
class_count = defaultdict(lambda: 0)

# Then put this right before text_str, line 219
class_count[_class] += 1
```
Then instead of `j` in the above `text_str` that you pasted in, use `class_count[_class]`.

I'll warn you that this code is untested, so might it have bugs (let me know).

**Comment by kim0207** [comment]
It works :)
Thank you for your help

**Comment by dbolya** [comment]
No problem. Lmk if you need anything else.

**Comment by kim0207** [comment]
Just a quick question.
How should I visualize individual instances on each image?

For like, If there are three cars, I want to visualize one car with mask at a time

**Comment by dbolya** [comment]
In the python version, you'd have to implement that yourself. But I have a web based detection viewer that has a lot more functionality (like selecting which detection to view, the ability to only show one detection at a time, etc.). However, the web version only works on COCO, so you'd need to make some changes to get it to work on your dataset. See #16 for how to use the web viewer.

**Comment by kim0207** [comment]
Thank you. So should I use the web version to visualize each instance at a time?
So if there are five instances, I wanted to save each instance on each image, which then five images will be saved

**Comment by dbolya** [comment]
Oh, if you want to save the images then you should probably just change something in the python version. The web version is meant for just viewing not saving.

Looking at the code, it would take quite a few changes to get the behavior you want (saving each mask to its own image on top of the original image), but you could just export the raw mask and draw them yourself if you want. That'd probably be easier.

If you want to do that, you just need to export this masks object
https://github.com/dbolya/yolact/blob/f46dc4385a41ed1f2df6716ecf6084081afcbec6/eval.py#L148
To convert it to numpy, use `masks.cpu().numpy()`.

**Comment by kim0207** [comment]
Can you tell me more?
Do you mean I can export the masks after converting it to numpy?

**Comment by dbolya** [comment]
I mean if you want to use the masks for your own stuff, you can save it by going
```
np.save('file_name.npy', masks.cpu().numpy())
```
It might be easier to export the masks and create a new script that uses them for exactly what you want than trying to retrofit what you want into my code.
