### ISSUE TITLE
confusion about the mask loss calculation

### ISSUE THREAD

**Issue by twangnh** [dbolya/yolact#106]
Hi, thanks for sharing the wonderful work, but I'm a little bit confused about the mask loss
https://github.com/dbolya/yolact/blob/f46dc4385a41ed1f2df6716ecf6084081afcbec6/layers/modules/multibox_loss.py#L541
https://github.com/dbolya/yolact/blob/f46dc4385a41ed1f2df6716ecf6084081afcbec6/layers/modules/multibox_loss.py#L550

seems the loss is normalized by box size, but why then times a weight of maskh*maskw, and then div maskh and maskw, which canceled the previous operation?

**Comment by dbolya** [comment]
There's that weird multiply then divide because previously in development we weren't cropping, and in that case you normalize by the entire image size. Once I added cropping and normalizing by bbox area, this was added as an additional setting. In order to keep everything backward compatible and so that I didn't have to rewrite a lot of things, I just cancelled out the earlier normalization.

As for the normalization by num_pos, that happens in the main function here:
https://github.com/dbolya/yolact/blob/f46dc4385a41ed1f2df6716ecf6084081afcbec6/layers/modules/multibox_loss.py#L191

**Comment by twangnh** [comment]
I see, thank you!

**Comment by twangnh** [comment]
https://github.com/dbolya/yolact/blob/6e22d1b1ccbeab4001bc6acd9124f5a679083d21/layers/modules/multibox_loss.py#L524-L525
I'm wondering, since there is already sigmoid activation for the predicted mask, why you still clamp them to 0-1

**Comment by dbolya** [comment]
I'll close this one since you opened a new issue for this (#108).
