### ISSUE TITLE
softmax issue

### ISSUE THREAD

**Issue by xuchengggg** [dbolya/yolact#111]
There is no softmax implemented in conf,  so, how is the value be limited within 0 to1 ? And I think probability can be more meaningful when it is displayed in the results.

**Comment by dbolya** [comment]
Not sure what you mean by that? The config has a setting for softmax right here:
https://github.com/dbolya/yolact/blob/6e22d1b1ccbeab4001bc6acd9124f5a679083d21/data/config.py#L347
And we use softmax for the class confidence branch as per the paper.

And FYI softmax is not nearly the only way too create a probability.

**Comment by xuchengggg** [comment]
I mean, i don't know where did you use the softmax. In detection.py, line 92, the shape of scores is [80, num_keep],  and i print the sum of (scores[: ,0]), which is larger than 1, and this means this is not the probability of the classes, and this score is also the score printed in the final result in eval.py line 219?

**Comment by dbolya** [comment]
Softmax is applied here:
https://github.com/dbolya/yolact/blob/6e22d1b1ccbeab4001bc6acd9124f5a679083d21/yolact.py#L615
Then line 92 in detection should actually sum to less than 1 for what you have there because 2 lines above, I create cur_scores by removing the background class (which I'd you include it should sum to 1). Double check and if it does sum to more that 1 there might be a problem.

And that is the score printed in eval.py, which should me the max of the 80 rows in that score matrix.

**Comment by xuchengggg** [comment]
0.0 , I think i use the older version of code, which didn't implement softmax, I will then use the new code to double check, thank you for your reply.
