### ISSUE TITLE
All the fpn layers shared one prediction head? 

### ISSUE THREAD

**Issue by feiyuhuahuo** [dbolya/yolact#112]
Firstly I guessed that each fpn layer has a prediction head according the code in 'yolact.py', but after I printed the model state_dict, there's only `prediction_layers.0.`. So all the results after different fpn layers go to the same prediction module?

**Comment by dbolya** [comment]
Yeah, all FPN layers use the same prediction head following the FPN and RetinaNet papers. The reason there is 5 different prediction head objects is so that it's possible in the config to have a unique one per layer. With these configs, however, that's disabled (it just added more parameters for no benefit) and one of them is the "parent", and the rest of the objects just use the parent's weights.

**Comment by feiyuhuahuo** [comment]
OK, got it.
