### ISSUE TITLE
Thanks for your work! Is YOLACT suitable for dense instance segmentation?

### ISSUE THREAD

**Issue by liugaolian** [dbolya/yolact#122]
Thank you for your work!
I'm using YOLACT for book spine instance segmentation, but the results are not good :
1). bad mask quality  
2). missed detection  （Maybe I can adjust the NMS threshold during the Inference phase ? ）

**As follows:**

![选区_013 png_017](https://user-images.githubusercontent.com/28881571/63632762-62a28b80-c66f-11e9-9a21-985090ef3fe7.png)

![选区_015 png_018](https://user-images.githubusercontent.com/28881571/63632819-81ede880-c670-11e9-9e6d-37f3df9da48d.png)

--------------------------------------------------------------------------------------------------------------
My training set has 1300 pictures and has trained 100,000 times. Loss value has been hovering around 2, no longer decline! 
The characteristics of the book spine object are **dense arrangement, inclination** and **large scale**. I would like to ask if the YOLACT model has the opportunity to complete my task. What shall I do? I look forward to your reply. Thank you very much.

**Comment by dbolya** [comment]
I'm not sure, since that's a pretty difficult task. Have you tried fine tuning instead of training from scratch? See #36 for a guide on how to do that.

Also, if you want to play with the NMS settings, you can do so in Yolact's constructor in `yolact.py` with the arguments to `Detect`'s constructor here: https://github.com/dbolya/yolact/blob/29e809e563d0c3e6c47c5c6716b8cc81686a2b24/yolact.py#L459

One thing you might want to try too, is that since this may be difficult for YOLACT because it's using boxes and with these slanted spines, the boxes are quite a bit larger than the mask, you could try intelligently rotating the image before sending it to YOLACT (both during training and testing).

Maybe train 2 models: one on the inclined results, and one on the upright results. Once you have the inclined model (you can just use this one tbh), you use the boxes to figure out the angle you need to rotate to get upright. An easy approach would be to assume the book runs along the diagonal of the box, and rotate the angle that diagonal makes with a side of the box (and average that out over all confident boxes).

Then, once you have your un-incliner, you apply that to your whole dataset and train another model to now predict the masks. Obviously, it would be half as slow, but it should be much more accurate than it is right now.

**Comment by liugaolian** [comment]
Thank you for your suggestion, very helpful, I wish you a smooth job!
