### ISSUE TITLE
How to measure time per frame in video?

### ISSUE THREAD

**Issue by kHarshit** [dbolya/yolact#131]
Hi,

First of all, thanks for the great work.

Can you give me an abstract explanation of how you calculate fps on video, I'm unable to understand the code in [`evalvideo()`](https://github.com/dbolya/yolact/blob/605b3c8fdf283642e7753c355bc6ee02f8db1380/eval.py#L601)?

I want to calculate the time on each frame separately in a video as follow:

e.g. 

```
time per frame:  0.25845866900635883   # first frame of video
time per frame:  0.261888614972122  # second frame of video, and so on...
time per frame:  0.25665648002177477
time per frame:  0.25639657099964097
time per frame:  0.25489152496447787
time per frame:  0.25707719300407916
time per frame:  0.2522949639824219
...
```
---
For example, to measure time on image, I use the following code in `evalimages()`:
```
def evalimages(...):
    start = timeit.default_timer()
    frame = torch.from_numpy(cv2.imread(path)).cuda().float()
    batch = FastBaseTransform()(frame.unsqueeze(0))
    preds = net(batch)
    stop = timeit.default_timer()
    print("Time on image: ", stop-start)
```

I want to do the same for each frame of video.

**Comment by dbolya** [comment]
But it already does that? Eval video right now is very highly parallelized. That is, all 4 steps needed to complete a frame happen at once so there's no way to time specifically one frame. The best you can do is to time those 4 steps together, and even though they're not all for the same frame, call it one frame (making it represent the average frame time).

If you want to show frame times instead of FPS, just modify this line (just replace fps with 1/fps for instance):
https://github.com/dbolya/yolact/blob/605b3c8fdf283642e7753c355bc6ee02f8db1380/eval.py#L742

You can also remove the `\r` at the beginning if you want to show each frame in the console (and not overwrite the previous frame's information).

Then processing FPS is how fast the images are being processed (i.e., as fast of a speed as possible), and playback FPS is how fast the video is being played back (capped at the video's native FPS).

If you want to time something that's sequential, go time `savevideo`. I had to make `evalvideo` as efficient as possible to make up for how slow python is as a language.

**Comment by kHarshit** [comment]
Thanks for your response @dbolya, I get it now.
