### ISSUE TITLE
Confusing about the difference of hyper-parameters between evaluating mAP and testing a image?

### ISSUE THREAD

**Issue by feiyuhuahuo** [dbolya/yolact#139]
Though it's a common case that use different hyper-parameters (e.g. confidence threshold, NMS threshold in yolov3 and additional top_k, score_threshold in yolact) when evaluating mAP and testing a image for detectors. But I'm still puzzling about it. I set the top_k=100, and score_threshold=0 when testing images in yolact. I do this to keep the detect process as same as evaluating mAP. Then I get results with too much boxes:
![000000153229](https://user-images.githubusercontent.com/32631344/64411478-d311c980-d0bf-11e9-9bf2-58a1d9ebdc0f.jpg)
If set score_threshold=0.3, then the result is much better:
![000000153229](https://user-images.githubusercontent.com/32631344/64411676-50d5d500-d0c0-11e9-8a63-1fda6aaee85a.jpg)
And if then evaluating mAP now, the mAP is about 26%.
So the hyper-parameters for highest mAP don't match with the best view result from human eye. I think this is strange. Shouldn't mAP be such a metric  that the higher the mAP is, the better for people watching.
Seems that detectors always do the above tricks, but i cannot figure out why.

**Comment by dbolya** [comment]
The reason is how the AP metric is calculated. It doesn't penalize having too many detections (in fact, it rewards having many low scoring detections).

AP is the integral of the precision-recall curve. To calculate it, you sort all your detections by score and mark each as a positive (if it matched with a gt) or a negative (if it didn't). Then you compute a running total of precision and recall to compute the integral. But notice that we sorted by score first, meaning that all our positive detections are likely to be early in the sort. Thus everything at the end with low score is likely a negative. If we add *more* negatives between those already almost 100% negatives, then that doesn't affect AP. However, if we add a positive, that increases mAP. This leads to the phenomenon where AP doesn't penalize having many low-scoring detections, and if one of those detections happens to be right, it actually rewards it.

Redmond moans about this toward the end of his YOLOv3 paper if you want some illustrations and reasoning from the big man himself:
https://pjreddie.com/media/files/papers/YOLOv3.pdf (See the last page rebuttal section, after he says "`Reviewer #4`").

This does indicate that mAP is kinda flawed, but I don't make the rules. ¯\\\_(ツ)\_/¯
