### ISSUE TITLE
Masks of the same class predicted as if being 1 object

### ISSUE THREAD

**Issue by Aya-tan** [dbolya/yolact#141]
Hello,

I managed to train on a custom dataset and get very good prediction results on instance segmentation, but all the masks on the image appear inside 1 box, as if being the same object.
Is there a parameter to change for each mask to be recognised as a different object? (in the annotations, there is 1 mask per object).

In 1 target, I have for instance 5 segmentations, and 1 bbox. Could this be the issue? Are the different masks supposed to be in different targets? I followed the instructions on [this post](https://github.com/dbolya/yolact/issues/70#issuecomment-504283008) to annotate my images so I don't understand why would the annotations be wrong but...

Thank you in advance for any insight on this.

**Comment by dbolya** [comment]
Uhh I'm not sure what you mean by that because in COCO, there's one mask per bbox. I haven't used labelme myself, but check the resulting JSON to see if it makes sense. You can do this by opening the json using the `json` package in python, then check the `'annotations'` list. That should have as many annotations as you have segmentations, so check if the length of that list is appropriate.

Then you should also check the bbox for those annotations to check if they surround the mask. Your bounding boxes should surround just the mask that's being predicted and include no padding around that, since that could confuse the network.

**Comment by Aya-tan** [comment]
Sorry, it turns out it was an issue with the labels. 
When using labelme, the different objects on the frame must have names differentiated by -#, for instance object-1, object-2 and not object1, object2.

**Comment by hande6688** [comment]
@melodie-r 
How to label a single category with labelme? After looking at the user-defined data set, there is no annotation naming method. For example, there is only one category in a graph: cat, cat, cat or CAT1, cat2, Cat3 or cat-0, cat-1, cat
