### ISSUE TITLE
Slow evaluation on video

### ISSUE THREAD

**Issue by Aya-tan** [dbolya/yolact#146]
Hello,

I am evaluating a custom model by displaying the result on a video in real time, and it ended up being very slow, with around 11 fps. It slows down to 6 fps when saving the video to another file.

I am using --video_multiframe=30 (I ran out of memory with 60), and I changed 'force_cpu_nms' to False in the config. Also, I am using a Windows environment with 1 NVIDIA K80 GPU, cuda8.0, cudatoolkits8.0, and Anaconda. 

Are there some parameters I could change to speed up the inference process ?

**Comment by dbolya** [comment]
Actually after like --video_multiframe=4, there's not much increase in speed so might as well just use a lower number.

As for your fps, it could be either that a K80 is too slow of a GPU, or your CPU could be too slow (python is plagued by being constantly CPU-bound because of the interpreter). What's your CPU? And have you tried the resnet50 version.

Also, what's the dimensions of your input video? Since the results are scaled back up to the input video size, that could take a long time if your video is like 4k or something.

**Comment by Aya-tan** [comment]
My CPU is an Intel Xeon with 2,30Ghz. I was trying the resnet101 version and haven't tried the resnet50 yet, I'll try it then !

My video's frames size is 1280x720, I guess I should try to resize it?

**Comment by dbolya** [comment]
Hmm 720p should be okay framerate-wise. I was definitely able to get 30+ fps with 720p. But yeah, your CPU and GPU are both slower than the machine all the benchmarks were done on, so I'm not surprised you can't hit 30 fps.

Resnet50 should get you much closer with only a little decrease in performance, so I recommend using that.

**Comment by Aya-tan** [comment]
So I tried using Resnet50 instead, but the video display in real time is at 13,5 fps on average. It's still better than 11 fps with Resnet101 though.
Also, with Resnet50, I observed that changing the --video_multiframe parameter value from 30 to 4 lowered the performance to 9fps.

I guess I need a better GPU and CPU to get closer to 30fps then. Thank you very much for your help!

**Comment by areebsyed** [comment]
@melodie-r @dbolya  when i try to save the live stream into another file the fps decreases alot too but main problem is that the new video file only always contains one frame. It doesnt record anything after that! I am also using 1280x720
