### ISSUE TITLE
rotated_yolact: generate rotated bounding boxes for rotated things

### ISSUE THREAD

**Issue by pandamax** [dbolya/yolact#150]
Thanks for your contribution again！

Maybe just a suggestion to expand the application of the model.Here is a model that has implemented for detecting rotated things,such as rotated pencil.

reference: 
https://github.com/mrlooi/rotated_maskrcnn

**Comment by dbolya** [comment]
That's cool for the specific case of rotated pencils and book spines and surf boards and stuff, but it looks like they do quite a bit worse overall. Maybe this type of issue doesn't come up often in real life?

**Comment by abhigoku10** [comment]
@pandamax thats a good suggestion @dbolya  but in real life if i want to train a model which will be used in the indoor environment and have depth estimation also then it will be very useful right

**Comment by dbolya** [comment]
@abhigoku10 Uhh this has nothing to do with depth. All this does is add the ability for rotated anchor boxes, which wouldn't help in cases where rotations of the same object aren't common.

Thus, it's useful for classifying items scatter on a table, but it's not useful when using an upright camera to view most of the world (of course, it becomes useful again if you rotate the camera).

It's a good idea for those cases where it'd help a lot, but since it performs worse on real, upright-camera data, I see no reason to implement it in this repo. You can definitely implement it in a fork, though!

There's at least some demand, so if you implement it, tell this guy: #122 :^ )

**Comment by piseabhijeet** [comment]
Hi,

Is there a way to regress the bounding boxes inside yolact? So instead of #122  where i might end up using 2 models - inclining cameras, de-inclining again. i can use rotated bboxes [x,y,x+w, y+h, theta] to get the masks as well as the best fitted bounding box?

Thanks in advance
