### ISSUE TITLE
Input image size on YOLACT

### ISSUE THREAD

**Issue by sdimantsd** [dbolya/yolact#159]
Hi, in the code there is a parameter name "cfg.max_size"
Did it means YOLACT resize the image to this size (to smaller/bigger size then the original image)?
If so, it's better to my to resize the image BEFOR send it to network, therfore i can use bigger k, am i right?

One more thing, when i eval image with 3840x2160 it's take about 0.04 sec.
but the same image with size 640x480 take 0.037 sec.
(I run this eval few times for each image of course)
The diffrent is  7.5%, can you explain this result?

Thanks so much!

**Comment by dbolya** [comment]
Okay, so the process is:

Original image -> resize to 550x550 -> run YOLACT -> output masks of size 550x550 -> resize masks to original image size.

So, resizing beforehand does the same thing as that second step, but forgoes the last step, which resizes all the way back to the original image size. So yes, it's better to resize them beforehand if you don't care about the final mask size being the same size as the image.

That's also the same reason why resizing to 640x480 first is faster, since you're not spending time resizing the 550x550 masks to 3840x2160 which can take a while with bilinear interpolation.

**Comment by sdimantsd** [comment]
OK, that make sense. 
Thanks!

**Comment by sdimantsd** [comment]
One more question, the 700 net is better then the 550 net? if so, what the relations?

thx

**Comment by dbolya** [comment]
Typically, using bigger images increases accuracy, but drastically lowers speed. You can see the specifics in the table in the readme: im700 is 4.6% more accurate (mAP) but 28.5% slower (fps).

I don't really recommend using im700 unless speed doesn't matter much for you.

**Comment by sdimantsd** [comment]
OK, thanks!
