### ISSUE TITLE
Combine multiple masks and boxes

### ISSUE THREAD

**Issue by luqinghit** [dbolya/yolact#168]
I want to apply Yolact to remote sensing images, UH,. Could you give me some Suggestions?
Thanks~

**Comment by dbolya** [comment]
If you can pose the problem as producing instance masks, you can use those predicted instance masks any way you want (including combining them). You'll want to do extra processing on YOLACT's output.

Also, I'll answer technical questions, but I can't help with open ended research questions since my hands are full already.

**Comment by luqinghit** [comment]
Fine,thank you~
