### ISSUE TITLE
Decimal point truncation when dividing integers with make_priors

### ISSUE THREAD

**Issue by yasudakn** [dbolya/yolact#189]
When converting to TorchScript with libtorch, bbox value is different from before conversion.
The cause seems to be the decimal point truncation when dividing the integer in make_priors.

Should be rewritten as follows:
```
                    # +0.5 because priors are in center-size notation
                    x = (i + 0.5) / float(conv_w)
                    y = (j + 0.5) / float(conv_h)
```

**Comment by dbolya** [comment]
You mean you modified the code to use TorchScript and it started using integer divison? If this is a code change you made (i.e., you added the TorchScript model), does this really need to be in the master branch? There are probably several places that I use regular division as float division because that's how it's defined in python3, so it sounds more like a bug in TorchScript.

Or if this is truncating in the current master, then that's a problem, but wouldn't that just make all boxes have `x=y=0`? Pretty sure that's not happening right now.

**Comment by yasudakn** [comment]
Certainly not happening in the current master branch. If it is a bug or specification of TorchScript that occurs after converting to TorchScript with jit.tracing, I think that another branch is also good.
Thank you and best regards.

**Comment by dbolya** [comment]
Ok thanks, I'll point others to this thread if they have the same problem.
