### ISSUE TITLE
Video Playback doesn't work

### ISSUE THREAD

**Issue by arossbach10** [dbolya/yolact#197]
I've been trying to play a video from a file, but the frames are not processed.

python eval.py --trained_model=weights/yolact_im700_54_800000.pth --score_threshold=0.15 --top_k=15 --video_multiframe=4 --video=input.mp4

I see this progress, but Video Playback is 0:
   Processing FPS: 26.02 | Video Playback FPS: 0.00 | Frames in Buffer: 104
The same for webcam.

For JPG images from file it works and I see the visualization with matplotlib.

Any idea?

**Comment by dbolya** [comment]
That's very weird. If you try saving the video out, what happens? (Just go `--video=input.mp4:output.mp4`)

**Comment by arossbach10** [comment]
The same.
I got a small output file, that was not usable.

**Comment by arossbach10** [comment]
The play_video thread seems not to work.

**Comment by dbolya** [comment]
Okay I just realized that a thread pool only processes exceptions when you get the result of it. So if there's an exception in the `play_video` thread (since .get() is never called on it), it wont print the exception. So, can you try wrapping the inside of `play_video` like this:
```python
def play_video():
    try:
        (...)
    except:
        import traceback
        traceback.print_exc()
```
(also getting on a flight soon so might not respond for a day)

**Comment by arossbach10** [comment]
Thank you for that.
No hurry, I can check it on Monday first.

I will send the results.

Am Sa., 2. Nov. 2019 um 00:22 Uhr schrieb Daniel Bolya <
notifications@github.com>:

**Comment by FantasyJXF** [comment]
Always crashed for video evaluating.

```
python eval.py --score_threshold=0.3 --video_multiframe=4 --video=test/ori_jay_960.mp4:results/out_mask1.mp4
Config not specified. Parsed yolact_resnet50_config from the file name.

Loading model... Done.
Initializing model... Done.

Processing FPS: 10.01 | Video Playback FPS: 0.00 | Frames in Buffer: 104
```

The repo is update so quickly, why not first solve this bug? @dbolya 
Is it necessary to use pool or sth here?

**Comment by dbolya** [comment]
The thing is, I can't reproduce the bug, so I can't really fix it. Can you make the change described above and report what the error was? Sounds like it could be an easy fix once we know what the error is.

**Comment by FantasyJXF** [comment]
OK, that's weird, it runs out the same problem on my Tesla P40 and V100 server.

Haven't try your solution, going to try now.

What's more, why not read and process each video frame in a loop,  does it need to use multithread?

Thanks for your quick reply.

**Comment by dbolya** [comment]
@FantasyJXF (It's not a solution, it'll just tell us what the error is).

The numbers reported in the paper for FPS are just running the model. They don't include 1.) loading the data, 2.) resizing the data and masks, 3.) drawing the masks, and 4.) displaying the resulting images (or saving them to disk otherwise). It's not just us that reports in this way, but instead everyone we compare against too. The standard way of timing is to just time the model after data transformation and stop when it outputs predictions.

The reason, I'm assuming, that no paper reports FPS with those slowdowns included is that those don't depend on the model so they can be done in parallel with the actual approach. The point of multithreading it here is to get the demo / save video speed to be as close as possible to the reported numbers in the paper (i.e. the --benchmark numbers) by doing all this in parallel with the main method. This is difficult because of Python's GIL meaning that only one instruction can run at once no matter how many threads you have, so I have to do a lot of weird tricks to improve on that.

**Comment by arossbach10** [comment]
> Okay I just realized that a thread pool only processes exceptions when you get the result of it. So if there's an exception in the `play_video` thread (since .get() is never called on it), it wont print the exception. So, can you try wrapping the inside of `play_video` like this:
> 
> ```python
> def play_video():
>     try:
>         (...)
>     except:
>         import traceback
>         traceback.print_exc()
> ```
> 
> (also getting on a flight soon so might not respond for a day)

I included your proposed code to print the exception and found the cause.

cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/highgui/src/window.cpp:626: error: (-2:Unspecified error) The function is not implemented.

For cv2.imshow() and waitkeys() dependencies were missing. The trace was helpfull to solve this.

**Comment by dbolya** [comment]
Thanks for figuring that out. I think that should still be classified as a bug on my part though, because saving a video should not depend on an environment with a display. I'll wrap `waitkeys()` to make sure it only gets called if you want to display something.

**Comment by FantasyJXF** [comment]
That's very useful.
