### ISSUE TITLE
How to change the layer number of the fourth stage network in resnet101?

### ISSUE THREAD

**Issue by niliuxi** [dbolya/yolact#199]
I want to change blocks = 64 to blocks = 4 in phase 4. How should I change it?

**Comment by dbolya** [comment]
I'm not sure what you mean by blocks=64 because blocks (the number of bottlenet blocks in a layer in Resnet) never goes above 23 for resnet101.

For Resnet101, you can see / change the number of blocks here:
https://github.com/dbolya/yolact/blob/04606f4075bb42b774676f195853d088c94571b9/data/config.py#L230

The way to read this is that there are 3 blocks between C1 and C2, 4 between C2 and C3, 23 between C3 and C4, and 3 between C4 to C5. To change the number of blocks, you can just change this list here (if using Resnet101, otherwise look at the other dataset definitions under that one).

**Comment by niliuxi** [comment]
thanks.^ ^
