### ISSUE TITLE
use_square_anchors

### ISSUE THREAD

**Issue by IMFinethankyou** [dbolya/yolact#220]
hi,@dbolya, wonderful idea of this model. I am studying your code, and found this is in the config file:
'use_square_anchors': True, # This is for backward compatability with a bug
'pred_aspect_ratios': [ [[1, 1/2, 2]] ]*5,
'pred_scales': [[24], [48], [96], [192], [384]],

"use square anchor" and the "aspect_ratio"  seem to be incompatible, you mentioned you accidently made everything square, can you give more detail about this, thank  you so much

**Comment by dbolya** [comment]
See #19 for my real-time reactions to that bug.

Essentially, the bug was the width and height were computed using the same formula so it's like if instead of aspect ratios, you had a 1x1 aspect ratio but the scales were `scale * sqrt(ar)`. So for 24 for instance, there's a 17x17 box, a 24x24 box, and a 34x34 box. If you're training from scratch, feel free to set that flag to False as it improves performance (see issue above).

**Comment by IMFinethankyou** [comment]
> See #19 for my real-time reactions to that bug.
> 
> Essentially, the bug was the width and height were computed using the same formula so it's like if instead of aspect ratios, you had a 1x1 aspect ratio but the scales were `scale * sqrt(ar)`. So for 24 for instance, there's a 17x17 box, a 24x24 box, and a 34x34 box. If you're training from scratch, feel free to set that flag to False as it improves performance (see issue above).

oh, I see, I checked the code, you have fixed this bug, so now the aspect-ratio can work, i will try that. thank you so much.
