### ISSUE TITLE
Error while using 8 GPUs.

### ISSUE THREAD

**Issue by ljjyxz123** [dbolya/yolact#234]
@dbolya 
Hello Daniel Bolya,

When I train yolact using 8 GPUs, my train command is as follow:
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python train.py --config=yolact_base_config --batch_size 8

But I got the error message after training a while, the error picture is attached.
![image](https://user-images.githubusercontent.com/2631417/70142653-b4c66480-16d4-11ea-9f21-dbceb7dcacbe.png)

But if I train by using 1 GPU, there will be no errors.

Do you know what happened while using 8 GPUs?

Thank you very much!

**Comment by dbolya** [comment]
So I don't disable batch norm when training because our default batch size is enough to keep batch norm from being unstable. However, when you use 8 GPUs with a batch size of 8, it's splitting that batch across all 8 gpus (1 per gpu), which has the same effect as using batch norm with a batch size of 1 (very unstable, loss blowing up is almost unavoidable).

I suggest using 8*8 for your batch size (so 8 per GPU) but you said in the other thread that something was wrong? The lowest I suggest going it 6*8. If you have to go any lower, I suggest either disabling batch norm or using fewer GPUs.

Though, are you on the latest version? MultiGPU scaling and automatic batch norm freezing are on the current master. Did you get a message that your batch norm was being frozen at the start of training?

**Comment by ljjyxz123** [comment]
> So I don't disable batch norm when training because our default batch size is enough to keep batch norm from being unstable. However, when you use 8 GPUs with a batch size of 8, it's splitting that batch across all 8 gpus (1 per gpu), which has the same effect as using batch norm with a batch size of 1 (very unstable, loss blowing up is almost unavoidable).
> 
> I suggest using 8_8 for your batch size (so 8 per GPU) but you said in the other thread that something was wrong? The lowest I suggest going it 6_8. If you have to go any lower, I suggest either disabling batch norm or using fewer GPUs.
> 
> Though, are you on the latest version? MultiGPU scaling and automatic batch norm freezing are on the current master. Did you get a message that your batch norm was being frozen at the start of training?

@dbolya 

Thank you for your reply.

When I was using batch_size as 64 (8 GPUs, and 8 batch per GPU), CUDA will be out of memory.
I think for 8 GPUs, the maximum batch_size can be 40 (8 GPUs, and 5 per GPU).
What do you suggest me to set batch_size in such situation?

I noticed that you updated the repo recently, I am not on the newest branch.
I didn't get a message that my batch norm was being frozen at the start of training. I only get the warning information at the start of training as being attached:
![image](https://user-images.githubusercontent.com/2631417/70196311-4e2c5f80-1743-11ea-8a9f-425aad1377c5.png)

Do you update the repo significantly in recent two months? I have modified a lot on the old versioned yolact, and wonder whether I need to keep updated with current version.

Thank you again~

**Comment by dbolya** [comment]
Yes, proper multigpu support was added a week or two ago (including a fix for that). I suggest you merge the current repo with your offline copy (it should be not too difficult through git). You should be able to do a higher batch size than 40 on current master, so try that.

**Comment by ljjyxz123** [comment]
> u should be able to do a higher batch size tha

@dbolya 
Thank you very much for updating!
