### ISSUE TITLE
A new idea: Can we generate mask coefficient and prototypes in the same convolutional layers?

### ISSUE THREAD

**Issue by ljjyxz123** [dbolya/yolact#237]
@dbolya 
Hello Daniel Bolya,
In your original paper, "Prediction Head" is in charge of generating mask coefficients, and "ProtoNet" is in charge of generating prototypes.

Can we use "ProtoNet" to generate both mask coefficients and prototypes? So as to let mask coefficients and prototypes can share the params in "ProtoNet" together.

Thank you!

**Comment by dbolya** [comment]
They already share the same backbone, but I see your point.

The reason mask coefficients are generated in the prediction head is that you need "instance-level" information somewhere in the network to tie masks to a specific instance. ProtoNet has no instance information, but the prediction head does which is why coefficients are generated there in the first place.

Now there are object detectors that repool features inside an instance box, so those features don't have to be instance-specific, but the end result can be. Check out R-FCN for details (it's what FCIS uses and they repool mask features). However, this has alignment issues and is slow because of repooling which is why we don't do it this way, but it's definitely possible.

**Comment by ljjyxz123** [comment]
> They already share the same backbone, but I see your point.
> 
> The reason mask coefficients are generated in the prediction head is that you need "instance-level" information somewhere in the network to tie masks to a specific instance. ProtoNet has no instance information, but the prediction head does which is why coefficients are generated there in the first place.
> 
> Now there are object detectors that repool features inside an instance box, so those features don't have to be instance-specific, but the end result can be. Check out R-FCN for details (it's what FCIS uses and they repool mask features). However, this has alignment issues and is slow because of repooling which is why we don't do it this way, but it's definitely possible.

@dbolya 
Okay, I see your point.
We need to instance specific information, which existed in the Prediction head, but not the ProtoNet head.
Thank you very much!

**Comment by dbolya** [comment]
No problem!
