### ISSUE TITLE
Changing input size of resnet101

### ISSUE THREAD

**Issue by sdimantsd** [dbolya/yolact#248]
Hi, thanks for your amazing work!
I what to use resnet101 as backbone but with input image size of 300x300.
I changed the size in config.py file and now i what to start training with this new size.
Can i use the pretraind weights in your README file even if i use diffrent input size? hot it is possible?

Thanx!

**Comment by dbolya** [comment]
Since we don't do any multiscale training, it's not recommended (the network is not used to a smaller image size and the features will look all weird). You can try it out by simply loading the pretrained weights with your new smaller image config, but I recommend training from scratch for performance.

**Comment by sdimantsd** [comment]
OK, thanks.
