### ISSUE TITLE
what's the difference the fast nms bewteen yolact and ssd

### ISSUE THREAD

**Issue by andeyeluguo** [dbolya/yolact#29]
I found  fastnms function in ssd code,so what's the difference between yolact and ssd?

**Comment by dbolya** [comment]
Can you give me a link to where you found this? As far as I know, we're the first to use this way to speed up NMS, but "Fast NMS" is a pretty generic name so it's possible others could have used the same name.

**Comment by andeyeluguo** [comment]
here

https://github.com/weiliu89/caffe/blob/4817bf8b4200b35ada8ed0dc378dceaf38c539e4/src/caffe/util/bbox_util.cpp#L1939

**Comment by dbolya** [comment]
That's not Fast NMS (as described in our paper), it's just traditional NMS. The name of the function, `ApplyNMSFast`, probably just indicates that they had a less efficient implementation before. Since their implementation of traditional NMS is pretty much exactly the Cython one we have in our repo for comparison (just with some abstraction), it's safe to say that that function is ~12ms slower than our "Fast NMS" algorithm (I'm starting to regret that name).
