### ISSUE TITLE
Multi-Label NMS

### ISSUE THREAD

**Issue by Auth0rM0rgan** [dbolya/yolact#339]
Hey @dbolya, I'm just curious to know, have you tried multi-label nms for Yolact? if yes, how was the performance compare to your proposed fast nms? 
Based on this repo https://github.com/tianzhi0549/FCOS, they were able to speeds up ResNe(x)t based models by up to 30% and MobileNet based models by 40%, with exactly the same performance.

Thanks

**Comment by dbolya** [comment]
Their original implementation of NMS was incredibly inefficient, and their implementation of multi-label NMS made it faster because they implemented it efficiently, so sadly other approaches won't see the same speed-up.

Fast NMS is already multi-label (this is what we call traditional NMS in our paper). It's just an approximate way to do it. Their original NMS "single-label NMS" is what we call cross-class NMS and if implemented right, it's faster than multi-label.

You can see this here: https://github.com/tianzhi0549/FCOS/issues/175#issuecomment-586350445
YOLO implements by default (here `multi_cls=False`) cross-class nms or "single-label NMS" and it's faster (but has worse performance) than their "multi-label NMS" (here `multi_cls=True`).

You can also do Fast cross-class NMS, and as expected it's faster but does worse than Fast (multi-class) NMS. I recon the FCOS guys would see a nice speed improvement with only a small hit to performance if they used our Fast NMS (basically compare "traditional NMS" and "fast NMS" in the ablation table in our paper).

That's my impression, at least. I might be understanding things wrong here.

**Comment by Auth0rM0rgan** [comment]
@dbolya, Thanks a lot!
