### ISSUE TITLE
Any idea  to transform eval result( box, masks, classes) to COCO  style ? the keypoint  is  how to change  masks to segmentations

### ISSUE THREAD

**Issue by stuafu** [dbolya/yolact#46]

**Comment by dbolya** [comment]
You mean you want to output detections as a COCO JSON?
To do that just run
```python eval.py <your eval parameters> --output_coco_json```
This will create the files `results/mask_detections.json` and `results/bbox_detections.json`.

**Comment by stuafu** [comment]
Not exactlly. i want to change the mask( which is an image) to points,    like  "segmentation": 
[1119,947,1144, 949, ...] .   then  i can use labelme to load the json file.

**Comment by dbolya** [comment]
You mean a collection of 2d points representing the "on" pixels in the mask? If I'm interpretting that correctly, then that seems like a really inefficient way to store a mask, but okay. To do that, all you need is to do a double loop through the mask (one for x and one for y) and add (x, y) to the list if the mask is a 1.

Or do you mean a polygon? I.e., the collection of points making up the edge of the mask with everything inside being filled in. If so, you'll have to find a library to do that yourself, since converting an image to a polygon is an involved computer vision algorithm in its own right (esp. since almost all masks are not convex).

Any mask representations other than the image representation I use internally and the RLE representation that COCO uses is out of the scope of the project though, so you'll have to do that stuff yourself.

**Comment by stuafu** [comment]
yes  i want to get polygon in  RLE representation . Thanks for your advice.  i think  i have to fit the polygon by every mask.

**Comment by dbolya** [comment]
Wait, the _polygon_ in RLE representation? Run Length Encoding is an encoding of the image, not a polygon. It works by encoding the image as the numbers of consecutive ones and zeros. So, `[100, 32, 200, 20]` means "100 zeros, then 32 ones, then 200 zeros, then 20 ones, then reshape the resulting list into an image". If that's what you want, I already output that in the COCO JSON, since that's COCO's format. Check the output of `--output_coco_json` for the segmentation. If you just want it in a different json structure, just load it into a python script and modify it from there.

**Comment by ridasalam** [comment]
Hi, i dont know if i understood your problem correctly but if you need coco style annotations from mask png, you can look into here:

http://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch

**Comment by stuafu** [comment]
Thanks dbolya and ridasalam .You have give a lot detail of that. i just want to covert predict result to a json file that can be loaded by labelme (an anntotation software for mask).Now i see  it should be done by personalself.

**Comment by dbolya** [comment]
This seems like a good time to close this issue. Feel free to reopen it or open a new issue if you need more help.

**Comment by 7eta** [comment]
@dbolya thanks dbolya but, **no create coco json**. How to work `--output_coco_json` ?
I typed `python eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.15 --top_k=3 --image=my_image.jpg --output_coco_json`
