### ISSUE TITLE
Whether data structures affect test results?

### ISSUE THREAD

**Issue by microshiftd** [dbolya/yolact#55]
Hi, It's me again.
After days of training, finally, I finished training my first yolact net. But surprising is more prominent than happiness.
Here is the problem.
For my dataset, pancreas and tumor are my labels. Due to fewer tumor images, the training set of pancreas and tumor labels were 7939 and 2252, respectively.  I don't know whether it is the above reason, my net ONLY LEARNED PANCREAS!  :(
May I ask is this normal? Is there a similar problem in the nature data set? I sincerely hope to know whether the model or the data cause the problem. If you have experience with this kind of problem, your advice will be essential!
Thanks a lot and hope for your reply.

**Comment by dbolya** [comment]
I haven't noticed Yolact failing to learn a class because there were fewer examples of it. For instance, there are very few "skiis" in the dataset, but it still learns it just fine. Are you sure there are no low confidence detections for tumors? (try turning down the `--score_threshold` to 0 and see what happens). You can also try to reduce the number of images in the dataset so that there are an equal amount of both classes.

And sorry about the long training time, I'm trying to improve that :(
