### ISSUE TITLE
can we plot the mAP of the training? 

### ISSUE THREAD

**Issue by linyingyingkarina** [dbolya/yolact#612]
I know now we only print out the mAP on validation. I want to know if it is possible to print out the mAP on training? Because, I want to know how well the model learn on my own dataset. Thanks.

**Comment by prsantiago** [comment]
I don´t think what you want makes sense, since in the training what you are tracking are the losses. Only in the validation you are generating the mask and bbox, which is what mAP measures.

But you can plot those results using the LogVisualizer class that comes in [logger.py](https://github.com/dbolya/yolact/blob/master/utils/logger.py). You can check https://github.com/dbolya/yolact/issues/78#issuecomment-582152293 for plotting the logs generated.

If I am wrong, please correct me.

**Comment by linyingyingkarina** [comment]
> I don´t think what you want makes sense, since in the training what you are tracking are the losses. Only in the validation you are generating the mask and bbox, which is what mAP measures.
> 
> But you can plot those results using the LogVisualizer class that comes in [logger.py](https://github.com/dbolya/yolact/blob/master/utils/logger.py). You can check [#78 (comment)](https://github.com/dbolya/yolact/issues/78#issuecomment-582152293) for plotting the logs generated.
> 
> If I am wrong, please correct me.

I think you are right. I might have a misunderstand. Thanks.
