### ISSUE TITLE
Which choose one of pytorch version on windows 10 ?

### ISSUE THREAD

**Issue by 7eta** [dbolya/yolact#646]
Hi. 
what is the best choice on windows 10?

some questions.

One . Is it compatible with latest pytorch?? on Miniconda(Anaconda) or still only old pytorch 1.0.1 ? 

Two. I have RTX 2080 Super, windows 10. can I run this code? No use `sh` command, No install `unzip`

Three. Can I use Python 3.7(or higher) ?

four. Please recommend system on windows10? ( eg. Python 3.7 / Pytorch X.X.X / CUDA XX.XX /  Cudnn XX.XX / Windows 10 )

**Comment by kidpaul94** [comment]
1. If you want to use YOLACT, I presume pytorch version doesn't really matter. If you want to use YOLACT++, you probably need to use some previous version of pytorch such as 1.4 because of an issue with DCNv2 currently imported in this folder. You can try to upgrade DCNv2: https://github.com/jinfagang/DCNv2_latest so that YOLACT++ is compatible with later pytorch version 
2. Yeap, you can totally do with that hardware setting.
3. You can use Python 3.7
4. Python 3.7 / Pytorch 1.4 / CUDA 11.2 was working alright when I tried it

**Comment by 7eta** [comment]
@kidpaul94 Thanks a lot.
I will try reinstall soon! Thank you. (but Windows 10.. )
Btw only install Python 3.7 ? or 3.7.x  (maximum 3.7.10)

**Comment by kidpaul94** [comment]
I presume that it doesn't matter.

**Comment by 7eta** [comment]
@kidpaul94 Thanks, I installed latest version!
