### ISSUE TITLE
instance segmentation for one class person.

### ISSUE THREAD

**Issue by GittersYang** [dbolya/yolact#65]
I want to get the instance of people.
How can I do to train coco for one class(person)?

**Comment by dbolya** [comment]
It's not too bad. Just open the COCO train and validation json annotations (data/coco/annotations) in python or something and in the annotations array, delete every annotation with category ID not equal to 1. Then save these modified annotations files and set up a custom dataset as specified in the readme. That should be all you need.

**Comment by GittersYang** [comment]
Oh, thanks for your Timely reply.

1. If I do what you saied，does the picture that does not contain a human instance contribute to training？
2. what's more, In addition to changing the annotations, what other operations do I need to do? for example, changing the dimensions of the vector, and the structure of the network, or something else.


I just started learning training models，so I asked some low-level questions. 
thank you very much for your reply. 

###  Thank you very very much!!

**Comment by dbolya** [comment]
1. I ignore all images with no annotations, so images without people wouldn't be considered (since you would have deleted all their annotations).
2. If you set up the dataset and config file as in the readme section for custom datasets (i.e. create a dataset config with the only class being "person" and follow the instructions in the readme) then the network will automatically reconfigure itself.

And don't hesitate to ask if you have any more questions :^ )

**Comment by GittersYang** [comment]
thanks for your timely reply.
I will try it like what you said

thank you very very much !!

**Comment by Tomhouxin** [comment]
I will also try to train one class(person), but I have a doubt that the final model will be larger,beause it base on resnet

**Comment by GittersYang** [comment]
why the final model will be larger?

**Comment by dbolya** [comment]
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.

**Comment by Dipali290** [comment]
how to delete all other annotations and keep only annotation belonging to person category
