### ISSUE TITLE
Why mAp is 0, even after so many iterations ?

### ISSUE THREAD

**Issue by mohanRajPartha** [dbolya/yolact#660]
Please help I am new to this, 
mAp is 0 even after this much iterations **92600** !! ,
```
[342]   92600 || B: 0.130 | C: 0.274 | M: 0.520 | S: 0.041 | T: 0.965 || ETA: 27 days, 23:08:49 || timer: 0.182
Computing validation mAP (this may take a while)...
Calculating mAP...

       |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |
  mask |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |  0.00 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
```

### settings
-- batch_size=1
If i set batch_size=5, getting an error "GPU out of memory"

### My dataset:
Training: 480 images (4302 * 2140)
Validate: 6 images (4302 * 2140)
Clases: 5

### config.py
```
# ----------------------- DATASETS ----------------------- #
CIRCUIT_CLASSES = ("circuitA1", "circuitA2", "circuitB1", "circuitB2", "circuitC1")

my_custom_dataset = dataset_base.copy({
    'name': 'Circuit Dataset',

    'train_images': './data/coco/images/train',
    'train_info':   './data/coco/annotations/train/instances_train.json',

    'valid_images': './data/coco/images/val',
    'valid_info':   './data/coco/annotations/val/instances_val.json',

    # Whether or not to load GT. If this is False, eval.py quantitative evaluation won't work.
    'has_gt': False,

    'class_names': CIRCUIT_CLASSES,

    # COCO class ids aren't sequential, so this is a bandage fix. If your ids aren't sequential,
    # provide a map from category_id -> index in class_names + 1 (the +1 is there because it's 1-indexed).
    # If not specified, this just assumes category ids start at 1 and increase sequentially.
    'label_map': { 1: 1, 2: 2, 3: 3, 4: 4, 5: 5 }
})
```
```
# ----------------------- YOLACT v1.0 CONFIGS ----------------------- #
yolact_base_config = coco_base_config.copy({
    'name': 'yolact_base',

    # Dataset stuff
    # 'dataset': coco2017_dataset,
    'dataset': my_custom_dataset,
    'num_classes': len(my_custom_dataset.class_names) + 1,

    # Image Size
    'max_size': 550,
    
    # Training params
    'lr_steps': (280000, 600000, 700000, 750000),
    'max_iter': 800000,
    
    # Backbone Settings
    'backbone': resnet101_backbone.copy({
        'selected_layers': list(range(1, 4)),
        'use_pixel_scales': True,
        'preapply_sqrt': False,
        'use_square_anchors': True, # This is for backward compatability with a bug

        'pred_aspect_ratios': [ [[1, 1/2, 2]] ]*5,
        'pred_scales': [[24], [48], [96], [192], [384]],
    }),

    # FPN Settings
    'fpn': fpn_base.copy({
        'use_conv_downsample': True,
        'num_downsample': 2,
    }),

    # Mask Settings
    'mask_type': mask_type.lincomb,
    'mask_alpha': 6.125,
    'mask_proto_src': 0,
    'mask_proto_net': [(256, 3, {'padding': 1})] * 3 + [(None, -2, {}), (256, 3, {'padding': 1})] + [(32, 1, {})],
    'mask_proto_normalize_emulate_roi_pooling': True,

    # Other stuff
    'share_prediction_module': True,
    'extra_head_net': [(256, 3, {'padding': 1})],

    'positive_iou_threshold': 0.5,
    'negative_iou_threshold': 0.4,

    'crowd_iou_threshold': 0.7,

    'use_semantic_segmentation_loss': True,
})
```

**Comment by Camilochiang** [comment]
Hei @mohanRajPartha 
- Have you solve your problem? if not try:
Change `CIRCUIT_CLASSES = ("circuitA1", "circuitA2", "circuitB1", "circuitB2", "circuitC1")`
For `CIRCUIT_CLASSES = ("circuitA1", "circuitA2", "circuitB1", "circuitB2", "circuitC1",)`
This solution has been proposed in several threads #504, #645 

- If you did solve your problem, is a good practice to close the issue once that is solve.

**Comment by takwaaa** [comment]
Hi everyone, i have a similar problem but with a custom test dataset . issue #763 
I'm using eval.py Map_calc function to evaluate my model on a test dataset (after it was already trained)  , but the result i got is all 0. 
![image](https://user-images.githubusercontent.com/51539404/175346468-1967347a-41c5-4c85-b250-318c5278da65.png)

does any one have an idea why and how can i fix it ? is that due to the fact that the custom dataset declaration has ****'has_gt'**: False** ? if that's the case than how can i get the mAP calculation result on a test dataset ?

**Comment by Camilochiang** [comment]
Mmm how did you train? Can you paste ur config.py?

**Comment by takwaaa** [comment]
> Mmm how did you train? Can you paste ur config.py?

Hello @Camilochiang ,
I train with this command `python train.py --config=yolact_resnet50_generated_dwg_config `

In config.py i have : 
```
# ----------------------- DATASETS ----------------------- #
DWG_GENERATED_CLASSES = ("object","cotation")
generated_dwg_dataset = dataset_base.copy({
    'name': 'DWG GENERATED',

    'train_images': './data/train/images',
    'valid_images': './data/val/images',

    'train_info': './data/train/annotations.json',
    'valid_info': './data/val/annotations.json',

    'class_names': ('object','cotation'),
    'label_map': { 1:  1, 2: 2 }
})

generated_dwg_Test_dataset = dataset_base.copy({
    'name': 'DWG GENERATED TEST',

    'valid_images': './data/test/images',
    'valid_info': './data/test/annotations.json',
    'has_gt': False,

    'class_names': ('object','cotation'),
    'label_map': { 1:  1, 2: 2 }
})

# ----------------------- YOLACT v1.0 CONFIGS ----------------------- #
yolact_resnet50_generated_dwg_config = yolact_resnet50_config.copy({
    'name': 'yolact_plus_resnet50_generated_dwg',
    # Dataset stuff
    'dataset': generated_dwg_dataset,
    'num_classes': len(generated_dwg_dataset.class_names) + 1,

    # Image Size
    'max_size': 350,
})
```

I then launch the test by this command `python eval.py --trained_model=weights/yolact_plus_resnet50_generated_dwg_3599_360000.pth --config yolact_resnet50_generated_dwg_config --output_coco_json  --score_threshold=0.1 --top_k=30 --dataset=generated_dwg_Test_dataset
`
i created a different database for the test : **generated_dwg_Test_dataset** which i defined in config.py, but now i want to evaluate my model , so i dumped the return of mAP_calc function in a file to see the mAP_calc result generated when i run eval.py on the test database and i got a table full of zeros !
What am i doing wrong ? 

- Isn't the mAP calculation function in eval.py supposed to calculate the mAP result on test dataset ? should i make the annotations file for the test dataset too ( because i only created a COCO dataset with just images and an empty annotation array) ? 

- How does the function work ? As far as i read the principle of mAP calculation is based on comparing the ground-truth bounding box /mask to the detected box/mask and returns a score . is that the case ? 

- and can you please explain to me what the first row of the mAP result consists of ? are those different IoU thresholds ?

![image](https://user-images.githubusercontent.com/51539404/175367666-bb492174-41e0-47b5-b8fe-07703ca742b6.png)


If that's the case , when using a custom test dataset, i fixed "has_gt" to False in dataset declaration ( config.py) , So in this case won't mAP calculation has no ground-truth labels to compare it to the preds values for it to process Map calculation?

I know i asked a lot of questions but i'm really confused and i'm trying to understand how this works ! 
Thanks

**Comment by Camilochiang** [comment]
- If you have non annotations for the test, is quite imposible to get a mAP
- Yep
- The row correspond to the error linked to diferent IoU thresholds
- Yep

**Comment by takwaaa** [comment]
hello, 
even after adding annotations for the test dataset , the Map calculation still returns 0 for all values . Why is that ? and how does the mAP calculation function in eval.py work exactly ?

**Comment by Camilochiang** [comment]
The definition is calc_map in eval.py
```
def calc_map(ap_data):
    print('Calculating mAP...')
    aps = [{'box': [], 'mask': []} for _ in iou_thresholds]

    for _class in range(len(cfg.dataset.class_names)):
        for iou_idx in range(len(iou_thresholds)):
            for iou_type in ('box', 'mask'):
                ap_obj = ap_data[iou_type][iou_idx][_class]

                if not ap_obj.is_empty():
                    aps[iou_idx][iou_type].append(ap_obj.get_ap())

    all_maps = {'box': OrderedDict(), 'mask': OrderedDict()}

    # Looking back at it, this code is really hard to read :/
    for iou_type in ('box', 'mask'):
        all_maps[iou_type]['all'] = 0 # Make this first in the ordereddict
        for i, threshold in enumerate(iou_thresholds):
            mAP = sum(aps[i][iou_type]) / len(aps[i][iou_type]) * 100 if len(aps[i][iou_type]) > 0 else 0
            all_maps[iou_type][int(threshold*100)] = mAP
        all_maps[iou_type]['all'] = (sum(all_maps[iou_type].values()) / (len(all_maps[iou_type].values())-1))
    
    print_maps(all_maps)
    
    # Put in a prettier format so we can serialize it to json during training
    all_maps = {k: {j: round(u, 2) for j, u in v.items()} for k, v in all_maps.items()}
    return all_maps
```
Did you also have this problem during training?

**Comment by mohanRajPartha** [comment]
@takwaaa
Have you tried to do the [Default training](https://github.com/dbolya/yolact#training) steps without any of the issues mentioned.
