### ISSUE TITLE
How pytorch parallel networks on a single gpu?

### ISSUE THREAD

**Issue by sj88eejqa** [dbolya/yolact#71]
Sorry maybe it's a trivial question, but it kind of confuses me a while. In the paper, it say that "we break the problem into parallel parts". However, the code in forward function seems to be serial. I can make break point in there using pdb.set_trace(). Do pytorch actually do it automatically for us, or something I just miss? Also, I wonder why don't add any extra bn layers. Could you explain it?

**Comment by dbolya** [comment]
Yeah Pytorch automatically runs CUDA calls asynchronously (and only waits for them to finish when the output is actually needed), so the parallel part is *supposed* to be running `self.proto_net(proto_x)` and `p = pred_layer(pred_x)` at the same time (which can be done on the same GPU because not all CUDA cores will be in use). But taking another look at the code, I use protonet's output right after I execute `self.proto_net(proto_x)`, so that's a moot point. I'll try reordering those operations later to see if it improves speed (but protonet only takes like 2-3ms to run anyway).

Though, when I wrote "parallel" I really meant "completely independent", not "can be executed asynchronously". Nevertheless, the latter is still desirable.

Also, we didn't add extra bn layers because we're trying not to rely on bn so we can remove it if we ever want to train with a lower batch size (bn layers really do require a batch size of at least ~8 to function properly). If during development we want to increase memory usage (and thus decrease batch size), we then have to freeze bn anyway. I might try a config with extra bn layers to see how well it works later though.
