### ISSUE TITLE
Classes trained in YOLACT

### ISSUE THREAD

**Issue by viet2411** [dbolya/yolact#79]
Hello,
I saw this video on Youtube(https://www.youtube.com/watch?v=k_T-okBKtmw&t=431s) and I think this work is great. But as you can see in the video, YOLACT did not detect trees, street lights, sky ..... How many classes did you train YOLACT on? I want to see instance segmentation on trees, street lights and other things.
Thank you and best regards.

**Comment by dbolya** [comment]
This was trained on COCO, which has [these 80 classes](https://github.com/dbolya/yolact/blob/b39f6d913d7cb70b6a55c5d9cd59f6ba066e8de6/data/config.py#L31). This does not include trees (though there is a potted plant class), street lights, or the sky, so that's why you weren't seeing it. You'd have to train on cityscapes if you want those kinds of classes.

**Comment by viet2411** [comment]
Thank you very much!! I'll try it in my research. 
Please keep up the good work!

**Comment by dbolya** [comment]
Thanks! I'll close this issue now, but feel free to reopen it or make a new one if you have more questions about this.
