### ISSUE TITLE
What is mask_alpha config and why did you say that it's just a "funky equation" ?

### ISSUE THREAD

**Issue by sanshibayuan** [dbolya/yolact#87]
When I trained on my custom dataset(coco-like), the Mask Loss was like 4000+,  so I checked the code and I saw that the mask_loss is multiplied by the mask_alpha config which is set as 0.4 / 256 * 140 * 140 in coco_base_config.

I was wondering is this important?

**Comment by dbolya** [comment]
Oh uh sounds like something's wrong there. Did you change the image size / number of prototypes or something?

That equation is just there because I've changed how I normalized the mask loss multiple times, and I wanted to keep the same mask alpha throughout. Also, that's not the mask alpha I actually use (it gets overwritten in `yolact_base_config`). The one I actually use is just 6.125 (which is also legacy, 6 works just as well), and is there to keep the magnitude of the mask loss similar to the other loss (hence why your 4k mask loss is a problem).

**Comment by ridasalam** [comment]
How did you come up with 6.125 as mask alpha? I changed some layers and I want to know how to retune this parameter. Thanks

**Comment by dbolya** [comment]
No method in particular. It's just that originally I had it set to like .4 or something to keep the losses the same magnitude, but then I changed how mask loss was normalized so I converted it to keep the loss weight the same through versions.

If you want to use the same method as me, just set it such that after like 1k iterations, the losses are all around the same magnitude.
