### ISSUE TITLE
Mask is weird around the edges

### ISSUE THREAD

**Issue by ridasalam** [dbolya/yolact#96]
<img width="239" alt="mask" src="https://user-images.githubusercontent.com/49155016/61174343-0c85f700-a59f-11e9-839a-fcc7393990ee.png">

Hi, I've noticed this weird behaviour around the mask edge. Any clue as to what would cause the curly lines?

Trained with my own dataset which has pretty good annotations around the edges.

**Comment by dbolya** [comment]
What's your image resolution? The mask resolution for the base version is ~140x140 and I use bilinear upsampling to output the mask with the same size as the image size. If your images are like 1000x1000 or something, then that's going to look pixelated (which is what's happening here--bilinear pixelation). If you think this is your problem, I've had someone email me with the same problem in the past and I can share the solutions I came up with.

**Comment by ridasalam** [comment]
Oh I see, yes I have pretty large images! What is your suggestion?

**Comment by dbolya** [comment]
So you could either use a smarter upsampling algorithm (like one of [these](https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms), but that would be difficult to implement in python), or have the model produce higher quality masks from the start. Both would add extra computation time, and the latter would add extra vram requirements to training (and require retraining), but I recommend the latter because it got good results for the other person.

You can increase the mask resolution one of two ways: increase the input image size (undesireable) or add an extra upsample-conv to Protonet. Right now Protonet has one bilinear upsample + conv (works better than a deconv in our experience) bringing it from the base 69x69 mask size to 138x138 or whatever. If you add an extra upsample+conv, it would output a resolution of 276x276 (and you can add more if you find this is not enough).

To add an extra upsample+conv, go to the config of the model you're interested in, and change `'mask_proto_net'` setting:
```python
'mask_proto_net': [(256, 3, {'padding': 1})] * 3 + [(None, -2, {}), (256, 3, {'padding': 1})] * 2 + [(32, 1, {})],
```
Note the `* 2` on the end there before `[(32, 1, {}],`. The current master branch only has one of those layer pairs, so this adds one more. If you want to add even more layer, you can increase that number more. You might have to tweak the mask alpha setting for really high resolutions if you add more than 2 upsample + conv layers, though.

**Comment by abhigoku10** [comment]
@ridasalam @dbolya even i faced the same issue with the resolution of 1280x720 for the network of resnet 101 , where the masks in few images were not in the complete shape, the detection bounding box was perfect . so for those scenarios also can i perform the above suggested approach ??

**Comment by dbolya** [comment]
@abhigoku10 The same suggested approach will work. Just add an extra upsample+conv to protonet. even 1280x720 is actually much larger than COCO's images, which I guess is why everyone's having this issue. 

So yeah, you can use the same fix to create arbitrarily large masks. And it's more efficient than if you'd do the same for say, Mask r-cnn, because there will only ever be 32 prototypes.
